version: "3.0"

services:
  db:
    image: mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pmysql"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    container_name: "api"
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8080:8080
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
